before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp .sample.env .env
  
  - psql -c 'create database "hola_mundo_test";' -U postgres
  
cache:
  - bundler
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.2.4
addons:
  postgresql: "9.3"
sudo: false
